const Icon = {
    logo : require("./logo.svg").default,
    arrowDown : require('./arrowDown.svg').default,
    buy : require("./Buy.svg").default,
    heart : require("./Heart.svg").default,
    search : require('./Search.svg').default,
    cellPhones : require('./cellphones.svg').default,
    saving : require('./Saving.svg').default,
    TVandVideo : require('./TVandVideo.svg').default,
    wearable : require('./WearableTechnologyT.svg').default,
    depart : require('.//Icon_Depart.svg').default,
    computer : require('./Computer.svg').default,
    beauty : require('./Beauty.svg').default,
    beverage : require('./Beverage.svg').default,
    candy : require('./Candy.svg').default,
    cocktails_caffe : require('./Cocktails_caffe.svg').default,
    CommunitiesSp : require('./CommunitiesSports.svg').default,
    feature_brands: require('./FeatureBrands.svg').default,
    feature_shop : require('./FeatureShop.svg').default,
    freshProduce : require('./FreshProduce.svg').default,
    frozen : require('./Frozen.svg').default,
    grocery : require('./Grocery.svg').default,
    premiumBeauty : require('./PremiumBeauty.svg').default,
    snack : require('./Snack.svg').default,
    TrendingBeauty : require('./TrendingBeauty.svg').default,
    BakeryBRead : require('./Bakery_Bread.svg').default,
    heart_active : require('./Heart_active.svg').default,
    star: require('./Star.svg').default,
    arror_right : require('./Arrow - Right 2.svg').default,
    bag : require('./Bag.svg').default,
    document : require('./Document.svg').default,
    starthalf : require('./Star-half.svg').default,
    startNone : require('./StarNone.svg').default,
    startReview : require('./StarReview.svg').default,
    plusIcon : require('./Plus.svg').default,
    subtractIcon : require('./subtract.svg').default,
    deleteIcon : require('./Delete.svg').default,
    dangerCircle : require('./Danger Circle.svg').default,
    downLoad : require('./Downlaod.svg').default,
    gift : require('./gift.svg').default,
    infoSquare : require('./Info Square.svg').default,
    location : require('./Location.svg').default,
    message : require('./Message.svg').default,
    personal : require('./Personal.svg').default,
    shieldDone : require('./Shield Done.svg').default,
    mainAvatar : require('./mainAvatar.svg').default,
    calling : require('./Calling.svg').default,
    
}
export default Icon;